name: reporte_aqui
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  file_picker: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  flutter_snake_navigationbar: ^0.6.1
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  mask_text_input_formatter: ^2.4.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
